$(document).ready(function(){
    $('.slider').slick({
        slidesToShow:2,
        slidesToScroll:1,
        autoplay:true,
        autoplaySpeed:3000,
        dots:true,
        arrows:true,
        responsive:[
            {
                breakpoint:768,
                settings:{
                    slidesToShow:1
                }
            }
        ]
    });

});